
name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]

    steps:
      - name: Set up Python 
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django

      - name: Set up Django
        run: |
          python manage.py migrate
          python manage.py collectstatic --noinput
      
      - name: Run tests
        run: |
          python ./simpleApp/manage.py test

